In [1]:
import pandas as pd

In [25]:
df = pd.read_csv('../data/train.tsv', sep='\t', header=None, names=["hate", "offense", "text"])

In [26]:
df.head()

hate  offense                                               text
0     0        0     Alarm set, early bird n all that. Night all xx
1     1        2  @EvanBecker513 @_TriggaPlease_ @MorbidMermaid ...
2     0        3      RT @_MindAtEase: Wet pussy with no smell a mf
3     0        3  RT @itsSamCollins: I hate seeing people with m...
4     0        3  &#8220;@RawrItsTaraa: Trust these bitches ? Na...

In [20]:
# Word tokenization
from spacy.lang.en import English
from spacy import displacy
import en_core_web_sm

# Load English tokenizer, tagger, parser, NER and word vectors
# nlp = English()
nlp = en_core_web_sm.load()

text = u"""New York City on Tuesday declared a public health emergency and ordered mandatory measles vaccinations amid an outbreak, becoming the latest national flash point over refusals to inoculate against dangerous diseases.

At least 285 people have contracted measles in the city since September, mostly in Brooklyn’s Williamsburg neighborhood. The order covers four Zip codes there, Mayor Bill de Blasio (D) said Tuesday.

The mandate orders all unvaccinated people in the area, including a concentration of Orthodox Jews, to receive inoculations, including for children as young as 6 months old. Anyone who resists could be fined up to $1,000."""

#  "nlp" Object is used to create documents with linguistic annotations.
my_doc = nlp(text)

# Create list of word tokens
token_list = []
for token in my_doc:
    token_list.append(token.text)
print(token_list)

entities=[(i, i.label_, i.label) for i in my_doc.ents]
entities

['New', 'York', 'City', 'on', 'Tuesday', 'declared', 'a', 'public', 'health', 'emergency', 'and', 'ordered', 'mandatory', 'measles', 'vaccinations', 'amid', 'an', 'outbreak', ',', 'becoming', 'the', 'latest', 'national', 'flash', 'point', 'over', 'refusals', 'to', 'inoculate', 'against', 'dangerous', 'diseases', '.', '\n\n', 'At', 'least', '285', 'people', 'have', 'contracted', 'measles', 'in', 'the', 'city', 'since', 'September', ',', 'mostly', 'in', 'Brooklyn', '’s', 'Williamsburg', 'neighborhood', '.', 'The', 'order', 'covers', 'four', 'Zip', 'codes', 'there', ',', 'Mayor', 'Bill', 'de', 'Blasio', '(', 'D', ')', 'said', 'Tuesday', '.', '\n\n', 'The', 'mandate', 'orders', 'all', 'unvaccinated', 'people', 'in', 'the', 'area', ',', 'including', 'a', 'concentration', 'of', 'Orthodox', 'Jews', ',', 'to', 'receive', 'inoculations', ',', 'including', 'for', 'children', 'as', 'young', 'as', '6', 'months', 'old', '.', 'Anyone', 'who', 'resists', 'could', 'be', 'fined', 'up', 'to', '$', '1,00

[(New York City, 'GPE', 382),
 (Tuesday, 'DATE', 388),
 (At least 285, 'CARDINAL', 394),
 (September, 'DATE', 388),
 (Brooklyn, 'GPE', 382),
 (Williamsburg, 'GPE', 382),
 (four, 'CARDINAL', 394),
 (Zip, 'PERSON', 378),
 (Bill de Blasio, 'PERSON', 378),
 (Tuesday, 'DATE', 388),
 (Orthodox, 'NORP', 379),
 (Jews, 'NORP', 379),
 (6 months old, 'DATE', 388),
 (1,000, 'MONEY', 391)]

In [21]:
displacy.render(my_doc, style = "ent",jupyter = True)

In [14]:
type(my_doc)

spacy.tokens.doc.Doc

In [15]:
import spacy
spacy_stopwords = spacy.lang.en.stop_words.STOP_WORDS

#Printing the total number of stop words:
print('Number of stop words: %d' % len(spacy_stopwords))

#Printing first ten stop words:
print('First ten stop words: %s' % list(spacy_stopwords)[:20])

Number of stop words: 305
First ten stop words: ['back', 'i', 'nobody', 'hence', 'put', 'above', 'myself', 'indeed', 'enough', 'during', 'herein', 'they', 'themselves', 'himself', 'please', 'we', 'among', 'yourselves', 'alone', 'only']


# Text Classificataion

In [107]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.base import TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

import string
from spacy.lang.en.stop_words import STOP_WORDS
from spacy.lang.en import English

# Create our list of punctuation marks
punctuations = string.punctuation

# Create our list of stopwords
nlp = spacy.load('en')
stop_words = spacy.lang.en.stop_words.STOP_WORDS

# Load English tokenizer, tagger, parser, NER and word vectors
parser = English()

# Creating our tokenizer function
def spacy_tokenizer(sentence):
    sentence = sentence.strip().lower()
    
    # Creating our token object, which is used to create documents with linguistic annotations.
    mytokens = parser(sentence)

    # Lemmatizing each token and converting each token into lowercase
    mytokens = [ word.lemma_.lower().strip() if word.lemma_ != "-PRON-" else word.lower_ for word in mytokens ]

    # Removing stop words
    mytokens = [ word for word in mytokens if word not in stop_words and word not in punctuations ]

    # return preprocessed list of tokens
    return mytokens

# Basic function to clean the text
def clean_text(text):
    # Removing spaces and converting text into lowercase
    return text.strip().lower()

# Custom transformer using spaCy
class predictors(TransformerMixin):
    def transform(self, X, **transform_params):
        # Cleaning Text
        return [clean_text(text) for text in X]

    def fit(self, X, y=None, **fit_params):
        return self

    def get_params(self, deep=True):
        return {}

# Load Data
df = pd.read_csv('../data/train.tsv', sep='\t', header=None, names=["hate", "offense", "text"])
df.head()

hate  offense                                               text
0     0        0     Alarm set, early bird n all that. Night all xx
1     1        2  @EvanBecker513 @_TriggaPlease_ @MorbidMermaid ...
2     0        3      RT @_MindAtEase: Wet pussy with no smell a mf
3     0        3  RT @itsSamCollins: I hate seeing people with m...
4     0        3  &#8220;@RawrItsTaraa: Trust these bitches ? Na...

In [110]:
bow_vector = CountVectorizer(tokenizer = spacy_tokenizer, ngram_range=(1,1))
bow_vector

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=<function spacy_tokenizer at 0x1a5616dc20>,
                vocabulary=None)

In [148]:
X = df['text'] # the features we want to analyze
y = df['hate'] # the labels, or answers, we want to test against

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# Vectorizer which uses the Spacy Tokenizer
bow_vector = CountVectorizer(tokenizer = spacy_tokenizer, ngram_range=(1,1))
tfidf_vector = TfidfVectorizer(tokenizer = spacy_tokenizer)

# Logistic Regression Classifier
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

classifier = LogisticRegression(max_iter=512)# LogisticRegression(max_iter=512)

# Create pipeline using Bag of Words
pipe = Pipeline([#('cleaner', predictors()),
                 ('vectorizer', bow_vector),
                 ('classifier', classifier)])

# model generation
pipe.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('vectorizer',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=<function spacy_tokenizer at 0x1a5616dc20>,
                                 vocabulary=None)),
                ('classifier',
                 LogisticRegression(C=1.0, class_weight=None, dual=False,
                                    fit_intercept=True, intercept_scaling=1,
                                    l1_ratio=None, max_iter=512,
           

In [142]:
import numpy as np
bins = np.arange(2, 7)
bins



array([-1,  2,  3,  4,  5,  6, 10])

In [146]:
from sklearn import metrics
from sklearn.preprocessing import KBinsDiscretizer
import numpy as np

# Predicting with a test dataset
predicted = pipe.predict(X_test)
print(predicted[0:10])
bins = np.concatenate(([min(predicted) - 1], bins, [max(predicted) + 1]), axis=None)

predicted = np.digitize(predicted, bins)
print(predicted[0:10])
print(y_test[0:10])

from sklearn import metrics
# Model Accuracy
print("Logistic Regression Accuracy:",metrics.accuracy_score(y_test, predicted))
print("Logistic Regression Precision:",metrics.precision_score(y_test, predicted, average='micro'))
print("Logistic Regression Recall:",metrics.recall_score(y_test, predicted, average='micro'))

[ 3.04174769 -0.1042171  -0.14861452 -0.17384757  0.89399207 -1.62686592
  1.00199956  0.83670408  0.38263013  0.39464244]
[5 3 3 3 3 3 3 3 3 3]
14376    0
9952     0
5678     0
12253    0
5356     0
17999    0
13347    0
5588     1
12805    0
4793     0
Name: hate, dtype: int64
Logistic Regression Accuracy: 0.008742434431741762
Logistic Regression Precision: 0.008742434431741762
Logistic Regression Recall: 0.008742434431741762


In [150]:
from sklearn import metrics
# Predicting with a test dataset
predicted = pipe.predict(X_test)

print(predicted[0:20])

# Model Accuracy
print("Logistic Regression Accuracy:",metrics.accuracy_score(y_test, predicted))
print("Logistic Regression Precision:",metrics.precision_score(y_test, predicted, average='micro'))
print("Logistic Regression Recall:",metrics.recall_score(y_test, predicted, average='micro'))

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 2 0 0 0 0 0]
Logistic Regression Accuracy: 0.7964021519838601
Logistic Regression Precision: 0.7964021519838601
Logistic Regression Recall: 0.7964021519838601


In [76]:
(y_test == predicted)[100:1000]

832       True
15486     True
12923     True
12076     True
11984    False
         ...  
10734     True
1974      True
12367     True
5299      True
18659     True
Name: hate, Length: 900, dtype: bool

In [70]:
X_test

15896    Aren't these little border jumpers supposed to...
10208    @TeamSky yellow in paris! Fantastic effort fro...
12852    @Pipe_Tyson Me? Nigga YOU the pussy. I got han...
2264     These hoes be actin up and these niccas be act...
329                                Ketchup on tha beat hoe
                               ...                        
11631    RT @Gawker: Conan O'Brien mocks the new Call o...
3603     @EmmaLouisaSuttl @timmyn90 Anyone bring in a m...
10860    @_That_Vibe_ bitch I'm Gretchen Weiners I do w...
18670    @Cheesus85 @greyyygoose faaaaggggottttt, speak...
11184    All these afternoon groups are trash besides t...
Name: text, Length: 5948, dtype: object

In [79]:
from scipy.stats import pearsonr

In [81]:
pearsonr(y_test, predicted)

(0.378756235581692, 3.1650023183655042e-202)

In [85]:
pearsonr([1,2,3,4,5], [3,4,6,8,10])

(0.9938837346736191, 0.0005736731093321747)

In [111]:
a = pearsonr(y_test, predicted)

In [112]:
a[1]

2.82826964511012e-188